### ISSUE TITLE
No package com.bugsense.trace

### ISSUE THREAD

**Issue by adarsh-tm** [nkts/nkts-android-temperature#1]
Hi, I tried to run the project but I get an error mesg "error: package com.bugsense.trace does not exist."

**Comment by nkts** [comment]
As this was one of my first projects - it doesn't include any dependency management. AFAIK BugSense were acquired by Splunk - not sure if that debug interface is working at the moment - I'm planing to remove that part.

**Comment by nkts** [comment]
Bugsense tracking code removed

**Comment by adarsh-tm** [comment]
Hi again, thank you for changing the code. I am trying to display a dummy temperature reading using the code you developed. I am quite new to this field. It would be really helpful if you tell me how exactly I can introduce a dummy temperature in your app.
